#!/usr/bin/env python3
"""Minimal PR body generator placeholder for the Git Sync skill."""

from __future__ import annotations

import json
import sys


def main() -> int:
    payload = json.load(sys.stdin)
    print(f"# {payload.get('title', 'multi-codex task')}\n")
    print("## Summary\n")
    print(payload.get("summary", "Generated by multi-codex Git Sync."))
    print("\n## Verification\n")
    for test in payload.get("tests_run", []):
        print(f"- {test}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
